// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjZ12Fa2Mvnn1O7vWcMUJm6G0o3jYi0Hk',
    appId: '1:735217303314:web:08a6e84c07eb2a3aa33dcb',
    messagingSenderId: '735217303314',
    projectId: 'smartconnect-f33b9',
    authDomain: 'smartconnect-f33b9.firebaseapp.com',
    storageBucket: 'smartconnect-f33b9.appspot.com',
    measurementId: 'G-D7Z3ERDTQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4zyzEBpcqhAv56QHb52EX9sQxo0N-Gvg',
    appId: '1:735217303314:android:ce695af6b7720164a33dcb',
    messagingSenderId: '735217303314',
    projectId: 'smartconnect-f33b9',
    storageBucket: 'smartconnect-f33b9.appspot.com',
  );
}
